backend:
  name: git-gateway
  branch: main

media_folder: "assets/projects"
public_folder: "/assets/projects"

collections:
  - name: "projects"
    label: "Danh sách Dự án"
    files:
      - label: "Các dự án"
        name: "project_list"
        file: "projects.json"
        fields:
          - {label: "ID Dự án", name: "id", widget: "string"}
          - {label: "Tên dự án", name: "title", widget: "string"}
          - {label: "Năm hoàn thành", name: "year", widget: "string"}
          - {label: "Địa điểm", name: "location", widget: "string", required: false}
          - {label: "Mô tả", name: "description", widget: "text", required: false}
          - {label: "Ảnh bìa", name: "thumbnail", widget: "image"}
          # Nơi tải lên hàng loạt ảnh chi tiết
          - label: "Tải lên toàn bộ ảnh chi tiết (Gallery)"
            name: "gallery"
            widget: "list"
            field: {label: "Ảnh", name: "image", widget: "image"}